# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Machine-learning-demo',
                'doc_host': 'https://lakebradford.github.io',
                'git_url': 'https://github.com/lakebradford/Machine-learning-demo',
                'lib_path': 'Machine_learning_demo'},
  'syms': {'Machine_learning_demo.core': {'Machine_learning_demo.core.foo': ('core.html#foo', 'Machine_learning_demo/core.py')}}}
